# templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-sre-tool-rolebinding
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: k8s-sre-tool
    namespace: monitoring
roleRef:
  kind: Role
  name: k8s-sre-tool-role
  apiGroup: rbac.authorization.k8s.io
