{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-sre-tool.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "k8s-sre-tool.labels" . | nindent 4 }}
{{- end }}