name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Current GitHub user running the workflow
          password: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./python
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/tyk-sre-tool:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/tyk-sre-tool:latest
